{{- if and (.Capabilities.APIVersions.Has "route.openshift.io/v1") (not .Values.ingress.rules) (not .Values.oauth2.enabled) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tesk-svc
spec:
  host: {{ .Values.host_name }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: tesk-api
    weight: 100
  wildcardPolicy: None
{{- end }}
{{- if and (.Capabilities.APIVersions.Has "route.openshift.io/v1") (not .Values.ingress.rules) (.Values.oauth2.enabled) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tesk-svc
spec:
  host: {{ .Values.host_name }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oauth2-proxy
    weight: 100
  wildcardPolicy: None

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tesk-token
spec:
  host: {{ .Values.host_name }}
  path: /token
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: oauth2-proxy-token
    weight: 100
  wildcardPolicy: None
{{- end }}